// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Sections/About.vue')['default']
    AsideMenu: typeof import('./src/components/Menu/AsideMenu.vue')['default']
    Authorship: typeof import('./src/components/Authorship/Authorship.vue')['default']
    Contacts: typeof import('./src/components/Sections/Contacts.vue')['default']
    CustomTransition: typeof import('./src/components/Transitions/CustomTransition.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    Experience: typeof import('./src/components/Sections/Experience.vue')['default']
    Footer: typeof import('./src/components/Footer/Footer.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Intro: typeof import('./src/components/Sections/Intro.vue')['default']
    Logo: typeof import('./src/components/Logo/Logo.vue')['default']
    Map: typeof import('./src/components/Map/Map.vue')['default']
    Photo: typeof import('./src/components/Photo/Photo.vue')['default']
    Skills: typeof import('./src/components/Skills/Skills.vue')['default']
    SocialMedia: typeof import('./src/components/SocialMedia/SocialMedia.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle/ThemeToggle.vue')['default']
    Timeline: typeof import('./src/components/Timeline/Timeline.vue')['default']
  }
}
